version: '2' 
services:
    db3:
      build: ./mariadb_local
      container_name: mariadb_aula3
      env_file:
        - ./env/db.env
      volumes:
        - db_data3:/var/lib/mysql
      networks:
        - net_db 
    wordpress:
      image: wordpress:5.3.0-php7.1-apache
      container_name: wordpress_aula3
      restart: always
      env_file:
        - ./env/wp.env
      volumes:
        - wordpress_p:/var/www/html
      ports:
        - 80:80
      networks:
        - net_db 
      depends_on:
        - db3      
    phpmyadmin3:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin_aula3
      env_file:
        - ./env/phpmy.env
      restart: always
      ports:
        - 8001:80
      volumes:
        - /sessions
      networks:
        - net_db 
      depends_on:
        - db3      
volumes:
    db_data3:
    wordpress_p:
networks:
    net_db:

