version: "2.2"

services:
  application:
    build: application
    links:
      - database
    ports:
      - "5000:5000"
    env_file:
      - ./env/app.env
    volumes:
      - ./application/src:/opt/application

  database:
    image: mariadb:10.4
    env_file:
      - ./env/mdb.env

